export let initialBoard = {
	a1: {
		color: 'white',
		piece: 'rook',
		image: '♖',
	},
	b1: {
		color: 'white',
		piece: 'knight',
		image: '♘',
	},
	c1: {
		color: 'white',
		piece: 'bishop',
		image: '♗',
	},
	d1: {
		color: 'white',
		piece: 'queen',
		image: '♕',
	},
	e1: {
		color: 'white',
		piece: 'king',
		image: '♔',
	},
	f1: {
		color: 'white',
		piece: 'bishop',
		image: '♗',
	},
	g1: {
		color: 'white',
		piece: 'knight',
		image: '♘',
	},
	h1: {
		color: 'white',
		piece: 'rook',
		image: '♖',
	},
	a2: {
		color: 'white',
		piece: 'pawn',
		image: '♙',
	},
	b2: {
		color: 'white',
		piece: 'pawn',
		image: '♙',
	},
	c2: {
		color: 'white',
		piece: 'pawn',
		image: '♙',
	},
	d2: {
		color: 'white',
		piece: 'pawn',
		image: '♙',
	},
	e2: {
		color: 'white',
		piece: 'pawn',
		image: '♙',
	},
	f2: {
		color: 'white',
		piece: 'pawn',
		image: '♙',
	},
	g2: {
		color: 'white',
		piece: 'pawn',
		image: '♙',
	},
	h2: {
		color: 'white',
		piece: 'pawn',
		image: '♙',
	},
	a3: { color: '', piece: '', image: '' },
	b3: { color: '', piece: '', image: '' },
	c3: { color: '', piece: '', image: '' },
	d3: { color: '', piece: '', image: '' },
	e3: { color: '', piece: '', image: '' },
	f3: { color: '', piece: '', image: '' },
	g3: { color: '', piece: '', image: '' },
	h3: { color: '', piece: '', image: '' },
	a4: { color: '', piece: '', image: '' },
	b4: { color: '', piece: '', image: '' },
	c4: { color: '', piece: '', image: '' },
	d4: { color: '', piece: '', image: '' },
	e4: { color: '', piece: '', image: '' },
	f4: { color: '', piece: '', image: '' },
	g4: { color: '', piece: '', image: '' },
	h4: { color: '', piece: '', image: '' },
	a5: { color: '', piece: '', image: '' },
	b5: { color: '', piece: '', image: '' },
	c5: { color: '', piece: '', image: '' },
	d5: { color: '', piece: '', image: '' },
	e5: { color: '', piece: '', image: '' },
	f5: { color: '', piece: '', image: '' },
	g5: { color: '', piece: '', image: '' },
	h5: { color: '', piece: '', image: '' },
	a6: { color: '', piece: '', image: '' },
	b6: { color: '', piece: '', image: '' },
	c6: { color: '', piece: '', image: '' },
	d6: { color: '', piece: '', image: '' },
	e6: { color: '', piece: '', image: '' },
	f6: { color: '', piece: '', image: '' },
	g6: { color: '', piece: '', image: '' },
	h6: { color: '', piece: '', image: '' },
	a7: {
		color: 'black',
		piece: 'pawn',
		image: '♟',
	},
	b7: {
		color: 'black',
		piece: 'pawn',
		image: '♟',
	},
	c7: {
		color: 'black',
		piece: 'pawn',
		image: '♟',
	},
	d7: {
		color: 'black',
		piece: 'pawn',
		image: '♟',
	},
	e7: {
		color: 'black',
		piece: 'pawn',
		image: '♟',
	},
	f7: {
		color: 'black',
		piece: 'pawn',
		image: '♟',
	},
	g7: {
		color: 'black',
		piece: 'pawn',
		image: '♟',
	},
	h7: {
		color: 'black',
		piece: 'pawn',
		image: '♟',
	},
	a8: {
		color: 'black',
		piece: 'rook',
		image: '♜',
	},
	b8: {
		color: 'black',
		piece: 'knight',
		image: '♞',
	},
	c8: {
		color: 'black',
		piece: 'bishop',
		image: '♝',
	},
	d8: {
		color: 'black',
		piece: 'queen',
		image: '♛',
	},
	e8: {
		color: 'black',
		piece: 'king',
		image: '♚',
	},
	f8: {
		color: 'black',
		piece: 'bishop',
		image: '♝',
	},
	g8: {
		color: 'black',
		piece: 'knight',
		image: '♞',
	},
	h8: {
		color: 'black',
		piece: 'rook',
		image: '♜',
	},
};
